# Change these first
owner: blaineam # Your GitHub organization or username, where this repository lives
repo: statussi # The name of this repository
user-agent: blaineam

sites:
  - name: BlaineAM Portfolio
    url: https://www.blaineam.com
    __dangerous__body_down_if_text_missing: 'Blaine Miller'
  - name: Miller's Cloud Directory
    url: https://millers.cloud
  - name: Miller's Cloud Sites
    url: https://sites.millers.cloud
  - name: 120 Media
    url: https://120.media
    __dangerous__body_down_if_text_missing: 'Romans 1:20'
  - name: Luma Friend
    url: https://luma.dog
    __dangerous__body_down_if_text_missing: 'Luma Friend'
  - name: Cenode Portfolio
    url: https://cenode.millers.cloud
    __dangerous__body_down_if_text_missing: 'Connecting our customers with their customers'
  - name: Featheread
    url: https://featheread.millers.cloud
    __dangerous__body_down_if_text_missing: 'Comedy'
  - name: Cache API
    url: https://cacheapi.millers.cloud
    __dangerous__body_down_if_text_missing: 'be here, now should you'
  - name: Cache Website
    url: https://cache.millers.cloud
    __dangerous__body_down_if_text_missing: 'Check out what makes Cache unique'
  - name: Blaine's CDN
    url: https://q6g1.c10.e2-1.dev/blaineam/data/static/media/images/theme/favicon.png
  - name: Miller's Cloud Go - Link Sharing
    url: https://go.millers.cloud/
  - name: Miller's Cloud Download - Media Downloader
    url: https://download.millers.cloud/
  - name: Miller's Cloud GPhotos - Google Photos Viewer
    url: https://gphotos.millers.cloud/
  - name: Miller's Cloud Pass - Password Manager
    url: https://pass.millers.cloud/
  - name: Miller's Cloud imgur - Imgur Album Uploader
    url: https://imgur.millers.cloud/
  - name: Miller's Cloud 360 - 360 Metadata Injector
    url: https://360.millers.cloud/
  - name: Miller's Cloud f2gp - Folders to Google Photos
    url: https://folderstogooglephotos.millers.cloud/
  - name: Miller's Cloud QR - QR Code Generator
    url: https://qr.millers.cloud/
  - name: Miller's Cloud SEO - SEO Report Generator
    url: https://seo.millers.cloud/
  - name: Miller's Cloud Barker - Fast Accountability
    url: https://barker.millers.cloud/
    __dangerous__body_down_if_text_missing: 'Blazing Fast Acountability for Every Device'
  - name: Miller's Cloud Analytics - Website Analytics
    url: https://analytics.millers.cloud/
  - name: Miller's Cloud Forms - Website Forms Utility
    url: https://forms.millers.cloud/
  - name: Miller's Cloud Help - Support Center
    url: https://help.millers.cloud/
  - name: Miller's Cloud WebScan - Site Scanning API
    url: https://webscan.millers.cloud/
    __dangerous__body_down_if_text_missing: 'Cloud Website Scanning'
  - name: Miller's Cloud Tools - Multi Tool Site
    url: https://tools.millers.cloud/
  - name: Miller's Cloud Puzzles - JigSaw Puzzles
    url: https://puzzles.millers.cloud/
  - name: Miller's Cloud Photos - Photo Editor
    url: https://photos.millers.cloud/
  - name: Miller's Home
    url: $SECRET_SITE_MILLERS_HOME
    expectedStatusCodes:
      - 0
      - 200
      - 201
  - name: Disciples Church
    url: https://discipleschurch.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.millers.cloud
  # baseUrl: /statussi
  logoUrl: https://q6g1.c10.e2-1.dev/blaineam/static/bmlogo.png
  name: Miller's Cloud Status
  introTitle: "This is the current state of the various Miller's Cloud Infrastructure"
  introMessage: "If there is an outage, Blaine will fix it as he has the time to do so."
  navbar:
    - title: Status
      href: /
assignees: # Users to assign downtime issues (optional)
  - blaineam
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
