# Change these first
owner: blaineam # Your GitHub organization or username, where this repository lives
repo: statussi # The name of this repository

sites:
  - name: BlaineAM Portfolio
    url: https://www.blaineam.com
  - name: Miller's Cloud Directory
    url: https://millers.cloud
  - name: Disciples Church
    url: https://discipleschurch.com
  - name: Miller's Cloud Sites
    url: https://sites.millers.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statussi.millers.cloud
  # baseUrl: /statussi
  logoUrl: https://q6g1.c10.e2-1.dev/blaineam/static/bmlogo.png
  name: Miller's Cloud Status
  introTitle: "This is the current state of the various Miller's Cloud Infrastructure"
  introMessage: "If there is an outage, Blaine will fix it as he has the time to do so."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
assignees: # Users to assign downtime issues (optional)
  - blaineam
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
